### ISSUE TITLE
TypeScript Epic

### ISSUE THREAD

**Issue by hamlim** [ds-pack/components#61]
I've been tinkering with TypeScript for the components in this repo, but everything is really loosely typed currently. My hope is to refine the types a bit and support a types file for other packages and applications to rely upon when using this package.

Here are the files that will benefit from being refined:

* [x] `src/Banner.tsx`
* [x] `src/Blockquote.tsx`
* [x] `src/Box.tsx`
* [x] `src/Button.tsx`
* [x] `src/Checkbox.tsx`
* [x] `src/Chip.tsx`
* [x] `src/Figure.tsx`
* [x] `src/GitHubMention.tsx`
* [x] `src/Heading.tsx`
* [x] `src/Image.tsx`
* [x] `src/InlineCode.tsx`
* [x] `src/Input.tsx`
* [x] `src/Label.tsx`
* [x] `src/Link.tsx`
* [x] `src/List.tsx`
* [x] `src/Stack.tsx`
* [x] `src/Tapable.tsx`
* [x] `src/Text.tsx`
* [x] `src/Textarea.tsx`
* [x] `src/ThemeProvider.tsx`
* [x] `src/ToggleInput.tsx`
* [x] `src/TwitterMention.tsx`
* [x] `src/useTapable.tsx`
* [x] `src/useTheme.tsx`
* [x] `src/VisuallyHidden.tsx`

In addition to the above, we also want to:

* [x] Setting up typescript to create a `.d.ts` file that is published to NPM

If you are interested in working on any of the above, feel free to comment on this issue with which one you want to take and I'll assign it to you!
